apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-nginx-demo
  namespace: jenkins
spec:
  selector:
    matchLabels:
      app: jenkins-demo
  template:
    metadata:
      labels:
        app: jenkins-demo
    spec:
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: jenkins-cicd     
      containers:
      - image: harbor.box.com/cicd/nginx-helloworld:<BUILD_TAG>
        imagePullPolicy: IfNotPresent
        name: jenkins-demo
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: cicd-nginx-helloworld
  name: cicd-nginx-helloworld
  namespace: jenkins
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30680
  selector:
    app: jenkins-demo
  type: NodePort
