apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-nginx-demo
spec:
  selector:
    matchLabels:
      app: jenkins-demo
  template:
    metadata:
      labels:
        app: jenkins-demo
    spec:
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: jenkins-cicd     
      containers:
      - image: harbor.box.com/cicd/nginx-helloworld:<BUILD_TAG>
        imagePullPolicy: IfNotPresent
        name: jenkins-demo
